#!/usr/bin/env bash
# Test for traceroute and curl

command -v traceroute >/dev/null 2>&1 || { echo >&2 "through requires traceroute to work."; exit 1; }
command -v curl >/dev/null 2>&1 || { echo >&2 "through requires geoiplookup to work."; exit 1; }

echo $'IP Address\t\tCity\t\tRegion\t\tCountry\t\tLatitude\tLongitude\tPostal'
traceroute "$1" | \
	awk '/^[:digit:]{1,3}\.[:digit:]{1,3}\.[:digit:]{1,3}\.[:digit:]{1,3}/ {print}'
#	curl ipinfo.io/`awk '/^[:digit:]{1,3}\.[:digit:]{1,3}\.[:digit:]{1,3}\.[:digit:]{1,3}/ {print}'`
