#!/usr/bin/env bash

# Test for traceroute, curl, and xml2
command -v traceroute >/dev/null 2>&1 || { echo >&2 "through requires traceroute to work."; exit 1; }
command -v curl >/dev/null 2>&1 || { echo >&2 "through requires geoiplookup to work."; exit 1; }
command -v xml2 >/dev/null 2>&1 || { echo >&2 "through requires xml2 to work."; exit 1; }

declare -a tracert=`traceroute "$1"`	# Run traceroute and store the results in $tracert
declare -a addresslist			# The list of IP Addresses in $tracert
declare -a info				# The formatted string displaying location data for all IP addresses
declare -a internaliplist		# The regexes for determining internal IP addresses
ipregex='[[:digit:]]\{1,3\}\.[[:digit:]]\{1,3\}\.[[:digit:]]\{1,3\}\.[[:digit:]]\{1,3\}'

# Iterate through the $tracert array and append all found IPv4 addresses to $addresslist
for i in "${tracert[@]}"; do
	if [[ $i != "" ]]; then #otherwise gives an error along the lines of  'file "" not found'.
			addresslist+=`grep -o $ipregex <<<"$tracert"`
	fi
done

# Print format for the $info string
printf "%-16s %-20s %-20s %-20s %-12s %-12s %-12s\n" "IP Address" "City" "Region" "Country" "Latitude" "Longitude" "Zip Code"

# Set up $info string 
for i in $addresslist; do
	declare -a item
	# skip internal IP addresses.
	if [[ `grep -o '10\.[[:digit:]]\{1,3\}\.[[:digit:]]\{1,3\}\.[[:digit:]]' <<< "$i"` != "$i" && \
		`grep -o '172.1[6-9]|2[0-9]|30|31\.[[:digit:]]\{1,3\}\.[[:digit:]]' <<< "$i"` != "$i" && \
		`grep -o '192\.168\.[[:digit:]]\{1,3\}\.[[:digit:]]\{1,3\}' <<< "$i"` != "$i" ]]; then
		item=`xml2 <<< $(curl -s freegeoip.net/xml/"$i")`		# Fetch location info for IP Address $i
		city=`sed -n -e 's/^.*\(City=\)//p' <<< "$item$"`
		region=`sed -n -e 's/^.*\(RegionName=\)//p' <<< "$item"`
		country=`sed -n -e 's/^.*\(CountryName=\)//p' <<< "$item"`
		latitude=`sed -n -e 's/^.*\(Latitude=\)//p' <<< "$item"`
		longitude=`sed -n -e 's/^.*\(Longitude=\)//p' <<< "$item"`
		zipcode=`sed -n -e 's/^.*\(ZipCode=\)//p' <<< "$item"`

		# Print the info for each IP Address
	       	printf "%-16s %-20s %-20s %-20s %-12s %-12s %-12s\n" "$i" "$city" "$region" "$country" "$latitude" "$longitude" "$zipcode"
	fi
done
